<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Choosephoto_button</name>
   <tag></tag>
   <elementGuidId>480ff543-e357-47c1-b291-4cce87154fa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.UxrKbK6rUr4vmo6SmCab > div.MF2rLXp4d_JPNs2t0bbj > button.xfQXUkj6ThzTYbfF8ilt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>70f5ffc6-29e8-433b-b49e-4bb600f5cd79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>edit-image-button</value>
      <webElementGuid>845205e3-aaf8-4771-a2dc-4acac788ed59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xfQXUkj6ThzTYbfF8ilt</value>
      <webElementGuid>8db74457-e523-4b8c-8358-292dcb6186f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d64df056-6325-4330-b9c8-e02b306a639d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5cfb7b76-4063-4dd8-8bf8-3e0c0278bec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose photo</value>
      <webElementGuid>bbb9ee79-c3a4-4de7-9bb3-dea12483a07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-focus-outline spotify__os--is-windows spotify__container--is-web&quot;]/body[@class=&quot;GenericModal__Body--open&quot;]/div[@class=&quot;ReactModalPortal&quot;]/div[@class=&quot;GenericModal__overlay&quot;]/div[@class=&quot;GenericModal encore-dark-theme&quot;]/div[@class=&quot;PiyAiXdQULEnWAHP0tu1&quot;]/div[@class=&quot;CU0wnmWejIvyEsRRtSac&quot;]/div[@class=&quot;ke5Pf1zkbk0eGnRWZYyg&quot;]/div[@class=&quot;UxrKbK6rUr4vmo6SmCab&quot;]/div[@class=&quot;MF2rLXp4d_JPNs2t0bbj&quot;]/button[@class=&quot;xfQXUkj6ThzTYbfF8ilt&quot;]</value>
      <webElementGuid>6a2fa24f-41a1-4ac4-b9a2-a4cb5b906dd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>53767030-fd49-48a0-abe2-351b1cf2e969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit details'])[1]/following::button[2]</value>
      <webElementGuid>7d2ed541-4e2a-4c78-b887-e5c313f50de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookie Policy.'])[1]/following::button[3]</value>
      <webElementGuid>7081aae1-2b2c-46b0-8ae8-4c787264a99a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit photo'])[1]/preceding::button[1]</value>
      <webElementGuid>270c31e0-0076-4cd4-b0c7-03c96b45cf80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/button</value>
      <webElementGuid>318690ac-6857-47de-9cd1-55ced875aebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Choose photo' or . = 'Choose photo')]</value>
      <webElementGuid>63ec8286-8d17-40c8-80ed-623e55e30b52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
