<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>namePlaylist_inputText</name>
   <tag></tag>
   <elementGuidId>faa6e96d-6514-47e6-9444-894009c21f38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text-input-84428d4df4ec8e51</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@type = 'text' and @placeholder = 'Add a name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b754f295-61c8-431f-826f-852f02fe2c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>playlist-edit-details-name-input</value>
      <webElementGuid>e9efbf0b-b5bd-40c5-8ffa-1e6abea94d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text-input-84428d4df4ec8e51</value>
      <webElementGuid>896c158f-93f1-463b-aa5e-8bc525127f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>394b51f2-9634-46a0-9ab9-4ebf010076ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f0GjZQZc4c_bKpqdyKbq JaGLdeBa2UaUMBT44vqI</value>
      <webElementGuid>c37908b1-3d5f-4369-9650-f970c2e0fdc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add a name</value>
      <webElementGuid>89a88449-5045-4dd6-bdc5-8e48821c08b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>My Playlist #99</value>
      <webElementGuid>71329c5c-745f-4f2e-a352-440b011122d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-input-84428d4df4ec8e51&quot;)</value>
      <webElementGuid>d64bc24e-acb0-4323-bfe6-ac6f962b5af7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text-input-84428d4df4ec8e51']</value>
      <webElementGuid>b22221be-f289-48fb-af5c-a059bf929861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>1bcc7596-0ede-49ca-80df-2714204ad4d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'text-input-84428d4df4ec8e51' and @type = 'text' and @placeholder = 'Add a name']</value>
      <webElementGuid>6c5c3403-1313-453a-881f-ec44b2d8d2f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
