<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Assert_send_OTP</name>
   <tag></tag>
   <elementGuidId>f35c0a94-1c68-4ea7-ae70-07a43e572869</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='verify-phone-number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#verify-phone-number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4a6c0281-8da6-4138-b298-b7df76da4bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verify-phone-number</value>
      <webElementGuid>f4cadbee-36e9-4b40-977f-85fd72d83940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>verify-phone-number</value>
      <webElementGuid>13a8f477-b5c7-4e44-94f0-6698a804fa1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Type__TypeElement-sc-goli3j-0 kwLSIj sc-kDvujY sc-dPWrhe kuHEmq deuyGK</value>
      <webElementGuid>58a4f8a5-25d5-4d99-80c5-a03f950d2cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-encore-id</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>c65a14ef-93fb-47f1-89ca-d0e1dc71e416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>We sent an SMS with a 6-digit code to +628999319766.</value>
      <webElementGuid>4ed0c9f7-b0b2-420f-9668-ed349ede1a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verify-phone-number&quot;)</value>
      <webElementGuid>ce282cd9-13c0-4a7d-a8f8-5dc137071166</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='verify-phone-number']</value>
      <webElementGuid>fb47a991-8a7f-42c4-bde9-37c96522d540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/p[2]</value>
      <webElementGuid>ec9e1bff-d721-459b-bcf7-7ebd15908e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::p[1]</value>
      <webElementGuid>a6baf6e4-9035-414f-bf9e-e8d55e37e867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get a new code'])[1]/following::p[1]</value>
      <webElementGuid>28983a79-a2ef-49fd-b62b-072abc5a49b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::p[1]</value>
      <webElementGuid>8b2fc673-8b8e-4eb7-ba95-5fe95d30ed53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::p[1]</value>
      <webElementGuid>6bde0edd-f0ee-4048-87e1-f3ad52a3d044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='We sent an SMS with a 6-digit code to +628999319766.']/parent::*</value>
      <webElementGuid>203a2b23-bb8e-43ba-9905-069d36e4dfc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>77246f81-3921-4f3b-a0dc-dee7499227bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'verify-phone-number' and (text() = 'We sent an SMS with a 6-digit code to +628999319766.' or . = 'We sent an SMS with a 6-digit code to +628999319766.')]</value>
      <webElementGuid>2ce0bde5-dceb-4331-b52d-2a676f6a1d18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
