<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Assert_Home</name>
   <tag></tag>
   <elementGuidId>6d5db476-5920-41c3-9942-bc2cb427e204</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/nav/div/ul/li/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.Type__TypeElement-sc-goli3j-0.jqNXli.ellipsis-one-line</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d7696428-7a80-44ef-8e25-45efb5de5b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Type__TypeElement-sc-goli3j-0 jqNXli ellipsis-one-line</value>
      <webElementGuid>d3006229-06e4-4bc0-b39c-e5ecff1b980d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-encore-id</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>e1a62e80-5328-4418-891e-8ea22bc9505b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>b07d39eb-683b-4b6e-a803-a735aa60e372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;Root encore-dark-theme&quot;]/div[@class=&quot;Root__top-container Root__top-container--right-sidebar-hidden&quot;]/nav[@class=&quot;Root__nav-bar&quot;]/div[@class=&quot;tUwyjggD2n5KvEtP5z1B&quot;]/ul[@class=&quot;RSg3qFREWrqWCuUvDpJR&quot;]/li[@class=&quot;eNs6P3JYpf2LScgTDHc6 InvalidDropTarget&quot;]/a[@class=&quot;link-subtle ATUzFKub89lzvkmvhpyE moDRd9td0KtitPDzR7OJ active&quot;]/span[@class=&quot;Type__TypeElement-sc-goli3j-0 jqNXli ellipsis-one-line&quot;]</value>
      <webElementGuid>eb617a7b-a071-4372-8d79-dd0c7153e606</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/nav/div/ul/li/a/span</value>
      <webElementGuid>c9f18b2d-f72b-4051-967c-68aa3ea0d6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upgrade'])[1]/following::span[2]</value>
      <webElementGuid>57d9fe25-6a31-4d76-94c7-653d4e38134c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::span[2]</value>
      <webElementGuid>1abbe592-c0c9-4c24-9fa9-745a1e0f4cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::span[1]</value>
      <webElementGuid>b30b5622-e9c0-4e58-b0ee-09fc34bca005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Library'])[1]/preceding::span[2]</value>
      <webElementGuid>418a385e-5fff-4ca7-ac43-eb59c96a5091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Home']/parent::*</value>
      <webElementGuid>338922b8-5d3a-4b5b-a679-65f90b581632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>44b28a3d-d297-44e9-93ea-0de5d47b04e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Home' or . = 'Home')]</value>
      <webElementGuid>eb7a6b57-dee4-4408-a16f-3856c9d33ede</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
