<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Next_button(OTP)</name>
   <tag></tag>
   <elementGuidId>e89e8496-83eb-433a-9861-6b771a882766</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='code-button']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ButtonInner-sc-14ud5tc-0.cJdEzG.encore-bright-accent-set</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b3cec1f2-ac6e-480e-8627-61d85e61afdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ButtonInner-sc-14ud5tc-0 cJdEzG encore-bright-accent-set</value>
      <webElementGuid>b124391a-b91b-48de-a837-7a5824623056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>6e4e2bb0-9a8f-4813-9e4c-e4238c46bf75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;code-button&quot;)/span[@class=&quot;ButtonInner-sc-14ud5tc-0 cJdEzG encore-bright-accent-set&quot;]</value>
      <webElementGuid>652794c2-2971-418a-8260-37a96b923bf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='code-button']/span</value>
      <webElementGuid>cbd2dc34-acaa-47b7-9cc4-5a64451e8e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get a new code'])[1]/following::span[1]</value>
      <webElementGuid>c88ac8bf-fc8b-4adf-bb88-b0261be80a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::span[3]</value>
      <webElementGuid>460a88f8-bded-40e4-9b20-a2d221d1ca17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>a5a52a85-4091-4acd-b912-a98ecaa40e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>0118b8f3-6be3-4f57-a43c-9ba48aa9b4e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
